development:
  adapter: mysql2
  database: doxnews_development
  pool: 5
  username: root
  password:
  encoding: utf8
  reconnect: true

test:
  adapter: mysql2
  database: doxnews_test
  pool: 5
  username: root
  password:
  encoding: utf8
  reconnect: true

production:
  adapter: mysql2
  database: doxnews_production
  pool: 5
  username: root
  password:
  encoding: utf8
  reconnect: true
